### ISSUE TITLE
Modding SWBF2 on linux without a copy of the game

### ISSUE THREAD

**Issue by TheAio** [marth8880/ZeroMunge#73]
Hi, is it at all possible to use this tool (or if anyone knows, any other tools) to mod starwars battlefront 2 via a linux machine?
and if so, then is it at all possible to do this without owning or obtaining a copy of the game?

For some context:
I have been asked to partake in a project to create a mod in SWBF2,
the issue is that i am running linux (linux mint) and also dont own a copy of the game.

**Comment by marth8880** [comment]
It might be possible with something like Wine, but not really too sure. The tools compile assets via batch files (which could probably be recreated into other kinds of files) that run compiler exes.

**Comment by TheAio** [comment]
okay, thanks.
Do you know if it would work without the game tho?
If it would work on linux at all that is

**Comment by marth8880** [comment]
I mean, technically you could compile mods without the game, but there would be no point if you can't even test them.

**Comment by TheAio** [comment]
Okay, thank you :)
I could perhaps test them by sending the mods to someone who has the game.

**Comment by TheAio** [comment]
Ill close the issue now, thanks for the fast replies.
